### ISSUE TITLE
capture_rsync.py deletes files when crossing midnight boundary

### ISSUE THREAD

**Issue by GLEANSUEMASU** [fmadio/fmadio_scripts#3]
検証環境は以下の通り。
キャプチャモードは"24/7 capture mode"でキャプチャ中。
FMADIO20<--->Storage(CentOS 6)

現象は下記の通り。
9月22日 14:00よりキャプチャを開始し、ほぼ同時にcapture_rsync.pyスクリプトも実行した。
実行コマンド
$ ./capture_rsync.py <capture_name> -- follow --compress --output <otuput dir>
※configファイルは作成済み。
9月22日 15:00時点でキャプチャ開始時のPCAPファイルがStorageに転送されていることを確認した。
9月22日 7:30時点でStorage内の最も古いファイルを確認したところ、9月22日 14:00時点のファイルがない。

問題点:
ユーザが意図せずに転送したはずのファイルが削除されている。

メモ：
本件、下記の３点を確認中。
　日付を超えた場合にのみ発生する現象か？
　quick capture modeでも同様に発生するか？
　<capture_name>を指定しない場合も再現するか？
上記３つが全て"Yes"の場合、動作仕様であるため、ドキュメントの修正のみで対応する。

**Comment by fmadio** [comment]
The test environment is as follow;

During capture with the capture mode of "24/7 capture mode".
FMADIO20<--->Storage(CentOS 6)

The phenomenons are as follow;

Sep.22: Started to capture at 14:00, executed capture_rsync.py script at almost the same time.
run command 
$ ./capture_rsync.py -- follow --compress --output 
※config file had been created.

Sep.22: Confirmed that the PCAP file created at the start of capture forwarded to the Storage at 15:00.

Sep.22: Checked the Storage for the oldest file at 7:30, could not find the file created at
14:00 Sep.22.

Issue:

The file an user should have been forwarded was unintentionally deleted. 

Memo:
Confirming 3 items below;

-Does the phenomenon only occur when exceed the date ?

-Does the phenomenon occur at quick capture mode ?

-Does the phenomenon occur if ~ is not designated ? 
*note by katsu: ~ is not mentioned original sentense.

If all those 3 items are "YES", they should be an issue about operating specifications
so I will respond by revising the document.

**Comment by fmadio** [comment]
**9月23日 7:30時点で**Storage内の最も古いファイルを確認したところ、9月22日 14:00時点のファイルがない。

９月２３日にですか？

**Comment by GLEANSUEMASU** [comment]
Sorry, I mistak, "23-sep" is correct.

**Comment by fmadio** [comment]
bug confimed

**Comment by GLEANSUEMASU** [comment]
Add information;
This issue is not happend when below condition. So this isuue is pendiing or change low priority.
この現象は次の条件下では発生しませんでした。だからこの問題は中断、もしくは優先度を下げます。
Codition;
a. Before the start of script, no caputre data in FMADIO20.
    FMADIO20内にキャプチャデータがないこと。
b. Without the capture name of options.
　キャプチャ名のオプションを指定しないこと。
c. The capture mode  is "24/7 mode".
　"24/7モード"であること。

**Comment by fmadio** [comment]
No change to FW required.

Many updates to rsync for midnight follow mode
fmadio/fmadio_scripts@12890f85151264a47f670c0a72eb291fb44f0667

Regression added: 
midnight cross + compressed follow mode
fmadio/fmadio20_regression@92f0915

**Comment by fmadio** [comment]
Note about Midnight cross.

capture_rsync.py is not a perfect 00:00:00.000.000.000 split. 

The last 23:59:59 capture will leak over to the next day by a few MSec.  e.g. stops 00:00:00.001.000.000

The new capture will start a few MSec after 00:00:00.000.000.000.

No packets are lost.

Some packets are duplicated

**Comment by GLEANSUEMASU** [comment]
I confirmed fix of the this issue.
I checked below;
 a. It is continuously file transfer
　->During capture, each 1min check.. It is not seems no trasfer.
 b. During capture, not stop scrypt.

Please this issue is close.
