### ISSUE TITLE
[PACKET BROWSER]: The file size not displayed

### ISSUE THREAD

**Issue by GLEANSUEMASU** [fmadio/fmadio_scripts#6]
The phenomenon:
In case of specify protocol. the file size not displayed how when file download.
プロトコルを指定してファイルダウンロードを行う場合、ファイルサイズが表示されない。

Operation
1. Menu -> [FILES]
2. [PACKET BROWSER] -> select [File]name
3. Select [UDP]
4. Select unit of split. ex) [split_1sec]
5. Displayed list, but not displayed [Bytes]/[GBytes]/[Packet Count]

Add information;
This isuue of operation did before analysis in [PACKET SCOPE].
この現象が起こる操作の前に[PACKET SCOPE]でanalysisは実行していない。

**Comment by fmadio** [comment]
This is correct behavior. To get this information it needs to parse the entire capture. The PCAP splitting process only uses metadata. The metadata does not contain tcp/udp/protocol information. There for  packet count / bytes can not be calculated.

**Comment by GLEANSUEMASU** [comment]
I understand. This isuue is close.

**Comment by fmadio** [comment]
there is plan to generate more detailed metadata. But no schedule yet.
